# This rule is not used by the project sec-gen-control itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to secrets.chinsecretgen.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sec-gen-control
    app.kubernetes.io/managed-by: kustomize
  name: mysecret-viewer-role
rules:
- apiGroups:
  - secrets.chinsecretgen.com
  resources:
  - mysecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.chinsecretgen.com
  resources:
  - mysecrets/status
  verbs:
  - get
