# This rule is not used by the project sec-gen-control itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over secrets.chinsecretgen.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sec-gen-control
    app.kubernetes.io/managed-by: kustomize
  name: mysecret-admin-role
rules:
- apiGroups:
  - secrets.chinsecretgen.com
  resources:
  - mysecrets
  verbs:
  - '*'
- apiGroups:
  - secrets.chinsecretgen.com
  resources:
  - mysecrets/status
  verbs:
  - get
